-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:db387e285dea6b92be6164a752b3fc8f:fa8fe6154d791f7d776c47b5decbdfdf:3010a86129a0a3dbdaf9892eab1a8ec9$
-- 

return {
	texture = 'gameScene.png',
	frames = {
			{
				name = "A-turret.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 47 },
				uvRect = { u0 = 0.123047, v0 = 0.25, u1 = 0.214844, v1 = 0.341797 },
				spriteSourceSize = { width = 47, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Abase1.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.732422, v0 = 0.330078, u1 = 0.814453, v1 = 0.402344 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Abase2.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.820312, v0 = 0.261719, u1 = 0.902344, v1 = 0.333984 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Abase3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.123047, v0 = 0.503906, u1 = 0.205078, v1 = 0.576172 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Abase4.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.210938, v0 = 0.464844, u1 = 0.292969, v1 = 0.537109 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Abigrocket1.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 76 },
				uvRect = { u0 = 0.580078, v0 = 0.00390625, u1 = 0.728516, v1 = 0.0507812 },
				spriteSourceSize = { width = 24, height = 76 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Abigrocket2.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.00390625, v0 = 0.466797, u1 = 0.0507812, v1 = 0.617188 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Abigrocket3.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.00390625, v0 = 0.3125, u1 = 0.0507812, v1 = 0.462891 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Abigrocket4.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 76 },
				uvRect = { u0 = 0.427734, v0 = 0.00390625, u1 = 0.576172, v1 = 0.0507812 },
				spriteSourceSize = { width = 24, height = 76 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Abigrocket5.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 76 },
				uvRect = { u0 = 0.275391, v0 = 0.00390625, u1 = 0.423828, v1 = 0.0507812 },
				spriteSourceSize = { width = 24, height = 76 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Abigrocketidle.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 51 },
				uvRect = { u0 = 0.228516, v0 = 0.158203, u1 = 0.328125, v1 = 0.205078 },
				spriteSourceSize = { width = 24, height = 51 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Afoggenerator.png",
				spriteColorRect = { x = 0, y = 1, width = 39, height = 56 },
				uvRect = { u0 = 0.732422, v0 = 0.169922, u1 = 0.841797, v1 = 0.246094 },
				spriteSourceSize = { width = 39, height = 60 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Agenerator1.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 59 },
				uvRect = { u0 = 0.361328, v0 = 0.0859375, u1 = 0.476562, v1 = 0.154297 },
				spriteSourceSize = { width = 35, height = 59 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Agenerator2.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 59 },
				uvRect = { u0 = 0.242188, v0 = 0.0859375, u1 = 0.357422, v1 = 0.154297 },
				spriteSourceSize = { width = 35, height = 59 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Agenerator3.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 59 },
				uvRect = { u0 = 0.123047, v0 = 0.0859375, u1 = 0.238281, v1 = 0.154297 },
				spriteSourceSize = { width = 35, height = 59 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Ainterceptor1.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 41 },
				uvRect = { u0 = 0.519531, v0 = 0.355469, u1 = 0.599609, v1 = 0.429688 },
				spriteSourceSize = { width = 38, height = 41 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Ainterceptor2.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 41 },
				uvRect = { u0 = 0.796875, v0 = 0.417969, u1 = 0.876953, v1 = 0.492188 },
				spriteSourceSize = { width = 38, height = 41 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Ainterceptor3.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 41 },
				uvRect = { u0 = 0.712891, v0 = 0.40625, u1 = 0.792969, v1 = 0.480469 },
				spriteSourceSize = { width = 38, height = 41 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Arobotback1.png",
				spriteColorRect = { x = 0, y = 4, width = 48, height = 36 },
				uvRect = { u0 = 0.332031, v0 = 0.158203, u1 = 0.425781, v1 = 0.228516 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotback2.png",
				spriteColorRect = { x = 0, y = 3, width = 48, height = 36 },
				uvRect = { u0 = 0.332031, v0 = 0.158203, u1 = 0.425781, v1 = 0.228516 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotback3.png",
				spriteColorRect = { x = 0, y = 2, width = 48, height = 36 },
				uvRect = { u0 = 0.332031, v0 = 0.158203, u1 = 0.425781, v1 = 0.228516 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotback4.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 36 },
				uvRect = { u0 = 0.332031, v0 = 0.158203, u1 = 0.425781, v1 = 0.228516 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotback5.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 36 },
				uvRect = { u0 = 0.332031, v0 = 0.158203, u1 = 0.425781, v1 = 0.228516 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotbase1.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.767578, v0 = 0.496094, u1 = 0.845703, v1 = 0.574219 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Arobotbase2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.880859, v0 = 0.429688, u1 = 0.958984, v1 = 0.507812 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Arobotbase3.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.59375, v0 = 0.492188, u1 = 0.671875, v1 = 0.570312 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Arobotbase4.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.685547, v0 = 0.484375, u1 = 0.763672, v1 = 0.5625 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Arobotfront1.png",
				spriteColorRect = { x = 0, y = 4, width = 52, height = 45 },
				uvRect = { u0 = 0.123047, v0 = 0.158203, u1 = 0.224609, v1 = 0.246094 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotfront2.png",
				spriteColorRect = { x = 0, y = 3, width = 52, height = 45 },
				uvRect = { u0 = 0.123047, v0 = 0.158203, u1 = 0.224609, v1 = 0.246094 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotfront3.png",
				spriteColorRect = { x = 0, y = 2, width = 52, height = 45 },
				uvRect = { u0 = 0.123047, v0 = 0.158203, u1 = 0.224609, v1 = 0.246094 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotfront4.png",
				spriteColorRect = { x = 0, y = 1, width = 52, height = 45 },
				uvRect = { u0 = 0.123047, v0 = 0.158203, u1 = 0.224609, v1 = 0.246094 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotfront5.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 45 },
				uvRect = { u0 = 0.123047, v0 = 0.158203, u1 = 0.224609, v1 = 0.246094 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arobotside1.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 47 },
				uvRect = { u0 = 0.472656, v0 = 0.166016, u1 = 0.564453, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Arobotside2.png",
				spriteColorRect = { x = 0, y = 3, width = 40, height = 47 },
				uvRect = { u0 = 0.472656, v0 = 0.166016, u1 = 0.564453, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Arobotside3.png",
				spriteColorRect = { x = 0, y = 2, width = 40, height = 47 },
				uvRect = { u0 = 0.472656, v0 = 0.166016, u1 = 0.564453, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Arobotside4.png",
				spriteColorRect = { x = 0, y = 1, width = 40, height = 47 },
				uvRect = { u0 = 0.472656, v0 = 0.166016, u1 = 0.564453, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Arobotside5.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 47 },
				uvRect = { u0 = 0.472656, v0 = 0.166016, u1 = 0.564453, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Arocketbase1.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.210938, v0 = 0.384766, u1 = 0.294922, v1 = 0.460938 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Arocketbase2.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.306641, v0 = 0.3125, u1 = 0.390625, v1 = 0.388672 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Arocketbase3.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.453125, v0 = 0.248047, u1 = 0.537109, v1 = 0.324219 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Arocketbase4.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.732422, v0 = 0.25, u1 = 0.816406, v1 = 0.326172 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Asmallrocket1.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 65 },
				uvRect = { u0 = 0.863281, v0 = 0.0664062, u1 = 0.990234, v1 = 0.09375 },
				spriteSourceSize = { width = 14, height = 65 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Asmallrocket2.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.257812, v0 = 0.0546875, u1 = 0.388672, v1 = 0.0820312 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Asmallrocket3.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.123047, v0 = 0.0546875, u1 = 0.253906, v1 = 0.0820312 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Asmallrocket4.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 66 },
				uvRect = { u0 = 0.525391, v0 = 0.0546875, u1 = 0.654297, v1 = 0.0820312 },
				spriteSourceSize = { width = 14, height = 66 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Asmallrocket5.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 66 },
				uvRect = { u0 = 0.392578, v0 = 0.0546875, u1 = 0.521484, v1 = 0.0820312 },
				spriteSourceSize = { width = 14, height = 66 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Asmallrocketidle.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 40 },
				uvRect = { u0 = 0.0859375, v0 = 0.375, u1 = 0.113281, v1 = 0.453125 },
				spriteSourceSize = { width = 14, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "B-turret.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 47 },
				uvRect = { u0 = 0.228516, v0 = 0.208984, u1 = 0.320312, v1 = 0.300781 },
				spriteSourceSize = { width = 47, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Bbase1.png",
				spriteColorRect = { x = 2, y = 4, width = 37, height = 42 },
				uvRect = { u0 = 0.298828, v0 = 0.392578, u1 = 0.380859, v1 = 0.464844 },
				spriteSourceSize = { width = 41, height = 48 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Bbase2.png",
				spriteColorRect = { x = 1, y = 3, width = 38, height = 43 },
				uvRect = { u0 = 0.123047, v0 = 0.425781, u1 = 0.207031, v1 = 0.5 },
				spriteSourceSize = { width = 40, height = 47 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Bbase3.png",
				spriteColorRect = { x = 1, y = 2, width = 37, height = 43 },
				uvRect = { u0 = 0.541016, v0 = 0.279297, u1 = 0.625, v1 = 0.351562 },
				spriteSourceSize = { width = 39, height = 47 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Bbase4.png",
				spriteColorRect = { x = 0, y = 1, width = 38, height = 42 },
				uvRect = { u0 = 0.433594, v0 = 0.328125, u1 = 0.515625, v1 = 0.402344 },
				spriteSourceSize = { width = 38, height = 46 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Bbigrocket1.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 76 },
				uvRect = { u0 = 0.123047, v0 = 0.00390625, u1 = 0.271484, v1 = 0.0507812 },
				spriteSourceSize = { width = 24, height = 76 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Bbigrocket2.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.00390625, v0 = 0.158203, u1 = 0.0507812, v1 = 0.308594 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Bbigrocket3.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.00390625, v0 = 0.00390625, u1 = 0.0507812, v1 = 0.154297 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Bbigrocket4.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 76 },
				uvRect = { u0 = 0.00390625, v0 = 0.773438, u1 = 0.0507812, v1 = 0.921875 },
				spriteSourceSize = { width = 24, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Bbigrocket5.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 76 },
				uvRect = { u0 = 0.00390625, v0 = 0.621094, u1 = 0.0507812, v1 = 0.769531 },
				spriteSourceSize = { width = 24, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Bbigrocketidle.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 51 },
				uvRect = { u0 = 0.0546875, v0 = 0.189453, u1 = 0.101562, v1 = 0.289062 },
				spriteSourceSize = { width = 24, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Bfoggenerator.png",
				spriteColorRect = { x = 0, y = 1, width = 39, height = 56 },
				uvRect = { u0 = 0.480469, v0 = 0.0859375, u1 = 0.589844, v1 = 0.162109 },
				spriteSourceSize = { width = 39, height = 60 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Bgenerator1.png",
				spriteColorRect = { x = 1, y = 0, width = 36, height = 59 },
				uvRect = { u0 = 0.00390625, v0 = 0.925781, u1 = 0.119141, v1 = 0.996094 },
				spriteSourceSize = { width = 38, height = 59 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Bgenerator2.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 59 },
				uvRect = { u0 = 0.851562, v0 = 0.0976562, u1 = 0.966797, v1 = 0.166016 },
				spriteSourceSize = { width = 35, height = 59 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Bgenerator3.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 59 },
				uvRect = { u0 = 0.732422, v0 = 0.0976562, u1 = 0.847656, v1 = 0.166016 },
				spriteSourceSize = { width = 35, height = 59 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Binterceptor1.png",
				spriteColorRect = { x = 1, y = 3, width = 38, height = 41 },
				uvRect = { u0 = 0.628906, v0 = 0.332031, u1 = 0.708984, v1 = 0.40625 },
				spriteSourceSize = { width = 40, height = 47 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Binterceptor2.png",
				spriteColorRect = { x = 0, y = 1, width = 39, height = 41 },
				uvRect = { u0 = 0.818359, v0 = 0.337891, u1 = 0.898438, v1 = 0.414062 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Binterceptor3.png",
				spriteColorRect = { x = 0, y = 3, width = 38, height = 41 },
				uvRect = { u0 = 0.902344, v0 = 0.351562, u1 = 0.982422, v1 = 0.425781 },
				spriteSourceSize = { width = 38, height = 47 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brobotback1.png",
				spriteColorRect = { x = 0, y = 4, width = 48, height = 36 },
				uvRect = { u0 = 0.658203, v0 = 0.0546875, u1 = 0.728516, v1 = 0.148438 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brobotback2.png",
				spriteColorRect = { x = 0, y = 3, width = 48, height = 36 },
				uvRect = { u0 = 0.658203, v0 = 0.0546875, u1 = 0.728516, v1 = 0.148438 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brobotback3.png",
				spriteColorRect = { x = 0, y = 2, width = 48, height = 36 },
				uvRect = { u0 = 0.658203, v0 = 0.0546875, u1 = 0.728516, v1 = 0.148438 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brobotback4.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 36 },
				uvRect = { u0 = 0.658203, v0 = 0.0546875, u1 = 0.728516, v1 = 0.148438 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brobotback5.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 36 },
				uvRect = { u0 = 0.658203, v0 = 0.0546875, u1 = 0.728516, v1 = 0.148438 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brobotbase1.png",
				spriteColorRect = { x = 1, y = 0, width = 40, height = 41 },
				uvRect = { u0 = 0.650391, v0 = 0.248047, u1 = 0.728516, v1 = 0.328125 },
				spriteSourceSize = { width = 42, height = 43 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotbase2.png",
				spriteColorRect = { x = 1, y = 1, width = 40, height = 40 },
				uvRect = { u0 = 0.511719, v0 = 0.433594, u1 = 0.589844, v1 = 0.511719 },
				spriteSourceSize = { width = 42, height = 42 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotbase3.png",
				spriteColorRect = { x = 1, y = 1, width = 40, height = 40 },
				uvRect = { u0 = 0.603516, v0 = 0.410156, u1 = 0.681641, v1 = 0.488281 },
				spriteSourceSize = { width = 42, height = 42 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotbase4.png",
				spriteColorRect = { x = 1, y = 2, width = 40, height = 40 },
				uvRect = { u0 = 0.429688, v0 = 0.40625, u1 = 0.507812, v1 = 0.484375 },
				spriteSourceSize = { width = 42, height = 44 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotfront1.png",
				spriteColorRect = { x = 0, y = 4, width = 52, height = 45 },
				uvRect = { u0 = 0.845703, v0 = 0.169922, u1 = 0.947266, v1 = 0.257812 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotfront2.png",
				spriteColorRect = { x = 0, y = 3, width = 52, height = 45 },
				uvRect = { u0 = 0.845703, v0 = 0.169922, u1 = 0.947266, v1 = 0.257812 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotfront3.png",
				spriteColorRect = { x = 0, y = 2, width = 52, height = 45 },
				uvRect = { u0 = 0.845703, v0 = 0.169922, u1 = 0.947266, v1 = 0.257812 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotfront4.png",
				spriteColorRect = { x = 0, y = 1, width = 52, height = 45 },
				uvRect = { u0 = 0.845703, v0 = 0.169922, u1 = 0.947266, v1 = 0.257812 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotfront5.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 45 },
				uvRect = { u0 = 0.845703, v0 = 0.169922, u1 = 0.947266, v1 = 0.257812 },
				spriteSourceSize = { width = 52, height = 49 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotside1.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 47 },
				uvRect = { u0 = 0.650391, v0 = 0.152344, u1 = 0.728516, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotside2.png",
				spriteColorRect = { x = 0, y = 3, width = 40, height = 47 },
				uvRect = { u0 = 0.650391, v0 = 0.152344, u1 = 0.728516, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotside3.png",
				spriteColorRect = { x = 0, y = 2, width = 40, height = 47 },
				uvRect = { u0 = 0.650391, v0 = 0.152344, u1 = 0.728516, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotside4.png",
				spriteColorRect = { x = 0, y = 1, width = 40, height = 47 },
				uvRect = { u0 = 0.650391, v0 = 0.152344, u1 = 0.728516, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brobotside5.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 47 },
				uvRect = { u0 = 0.650391, v0 = 0.152344, u1 = 0.728516, v1 = 0.244141 },
				spriteSourceSize = { width = 44, height = 51 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Brocketbase1.png",
				spriteColorRect = { x = 0, y = 2, width = 39, height = 43 },
				uvRect = { u0 = 0.123047, v0 = 0.345703, u1 = 0.207031, v1 = 0.421875 },
				spriteSourceSize = { width = 39, height = 49 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brocketbase2.png",
				spriteColorRect = { x = 1, y = 0, width = 39, height = 44 },
				uvRect = { u0 = 0.324219, v0 = 0.232422, u1 = 0.410156, v1 = 0.308594 },
				spriteSourceSize = { width = 41, height = 46 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brocketbase3.png",
				spriteColorRect = { x = 1, y = 1, width = 39, height = 43 },
				uvRect = { u0 = 0.21875, v0 = 0.304688, u1 = 0.302734, v1 = 0.380859 },
				spriteSourceSize = { width = 41, height = 45 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Brocketbase4.png",
				spriteColorRect = { x = 0, y = 1, width = 40, height = 43 },
				uvRect = { u0 = 0.568359, v0 = 0.191406, u1 = 0.646484, v1 = 0.275391 },
				spriteSourceSize = { width = 42, height = 45 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bsmallrocket1.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 65 },
				uvRect = { u0 = 0.732422, v0 = 0.0664062, u1 = 0.859375, v1 = 0.09375 },
				spriteSourceSize = { width = 14, height = 65 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Bsmallrocket2.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.732422, v0 = 0.0351562, u1 = 0.863281, v1 = 0.0625 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Bsmallrocket3.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.732422, v0 = 0.00390625, u1 = 0.863281, v1 = 0.03125 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Bsmallrocket4.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 66 },
				uvRect = { u0 = 0.867188, v0 = 0.0351562, u1 = 0.996094, v1 = 0.0625 },
				spriteSourceSize = { width = 14, height = 66 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Bsmallrocket5.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 66 },
				uvRect = { u0 = 0.867188, v0 = 0.00390625, u1 = 0.996094, v1 = 0.03125 },
				spriteSourceSize = { width = 14, height = 66 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "Bsmallrocketidle.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 40 },
				uvRect = { u0 = 0.0546875, v0 = 0.375, u1 = 0.0820312, v1 = 0.453125 },
				spriteSourceSize = { width = 14, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expbig01.png",
				spriteColorRect = { x = 14, y = 14, width = 13, height = 11 },
				uvRect = { u0 = 0.970703, v0 = 0.0976562, u1 = 0.996094, v1 = 0.119141 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig02.png",
				spriteColorRect = { x = 10, y = 10, width = 21, height = 19 },
				uvRect = { u0 = 0.951172, v0 = 0.230469, u1 = 0.992188, v1 = 0.267578 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig03.png",
				spriteColorRect = { x = 6, y = 6, width = 27, height = 25 },
				uvRect = { u0 = 0.59375, v0 = 0.138672, u1 = 0.646484, v1 = 0.1875 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig04.png",
				spriteColorRect = { x = 5, y = 5, width = 31, height = 29 },
				uvRect = { u0 = 0.0546875, v0 = 0.0683594, u1 = 0.115234, v1 = 0.125 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig05.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 39 },
				uvRect = { u0 = 0.90625, v0 = 0.271484, u1 = 0.986328, v1 = 0.347656 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expbig06.png",
				spriteColorRect = { x = 2, y = 0, width = 37, height = 37 },
				uvRect = { u0 = 0.675781, v0 = 0.566406, u1 = 0.748047, v1 = 0.638672 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig07.png",
				spriteColorRect = { x = 2, y = 1, width = 37, height = 35 },
				uvRect = { u0 = 0.373047, v0 = 0.488281, u1 = 0.445312, v1 = 0.556641 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig08.png",
				spriteColorRect = { x = 1, y = 1, width = 37, height = 35 },
				uvRect = { u0 = 0.296875, v0 = 0.46875, u1 = 0.369141, v1 = 0.537109 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig09.png",
				spriteColorRect = { x = 2, y = 1, width = 35, height = 35 },
				uvRect = { u0 = 0.449219, v0 = 0.515625, u1 = 0.517578, v1 = 0.583984 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig10.png",
				spriteColorRect = { x = 5, y = 3, width = 31, height = 31 },
				uvRect = { u0 = 0.0546875, v0 = 0.00390625, u1 = 0.115234, v1 = 0.0644531 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig11.png",
				spriteColorRect = { x = 6, y = 4, width = 29, height = 29 },
				uvRect = { u0 = 0.0546875, v0 = 0.128906, u1 = 0.111328, v1 = 0.185547 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig12.png",
				spriteColorRect = { x = 6, y = 7, width = 27, height = 25 },
				uvRect = { u0 = 0.59375, v0 = 0.0859375, u1 = 0.646484, v1 = 0.134766 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig13.png",
				spriteColorRect = { x = 10, y = 6, width = 21, height = 25 },
				uvRect = { u0 = 0.951172, v0 = 0.177734, u1 = 0.992188, v1 = 0.226562 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expmid1.png",
				spriteColorRect = { x = 1, y = 1, width = 15, height = 16 },
				uvRect = { u0 = 0.394531, v0 = 0.386719, u1 = 0.425781, v1 = 0.416016 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expmid2.png",
				spriteColorRect = { x = 0, y = 1, width = 17, height = 18 },
				uvRect = { u0 = 0.394531, v0 = 0.314453, u1 = 0.429688, v1 = 0.347656 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expmid3.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.429688, v0 = 0.199219, u1 = 0.46875, v1 = 0.236328 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid4.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.0546875, v0 = 0.333984, u1 = 0.09375, v1 = 0.371094 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid5.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.0546875, v0 = 0.292969, u1 = 0.09375, v1 = 0.330078 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid6.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.429688, v0 = 0.158203, u1 = 0.46875, v1 = 0.195312 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid7.png",
				spriteColorRect = { x = 1, y = 1, width = 17, height = 18 },
				uvRect = { u0 = 0.414062, v0 = 0.277344, u1 = 0.449219, v1 = 0.310547 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expmid8.png",
				spriteColorRect = { x = 0, y = 2, width = 17, height = 16 },
				uvRect = { u0 = 0.394531, v0 = 0.351562, u1 = 0.427734, v1 = 0.382812 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expmid9.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 18 },
				uvRect = { u0 = 0.414062, v0 = 0.240234, u1 = 0.449219, v1 = 0.273438 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expsmall1.png",
				spriteColorRect = { x = 3, y = 3, width = 2, height = 2 },
				uvRect = { u0 = 0.990234, v0 = 0.123047, u1 = 0.994141, v1 = 0.126953 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall2.png",
				spriteColorRect = { x = 0, y = 0, width = 8, height = 8 },
				uvRect = { u0 = 0.970703, v0 = 0.142578, u1 = 0.986328, v1 = 0.158203 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expsmall3.png",
				spriteColorRect = { x = 0, y = 0, width = 8, height = 8 },
				uvRect = { u0 = 0.970703, v0 = 0.123047, u1 = 0.986328, v1 = 0.138672 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expsmall4.png",
				spriteColorRect = { x = 0, y = 1, width = 8, height = 6 },
				uvRect = { u0 = 0.970703, v0 = 0.162109, u1 = 0.986328, v1 = 0.173828 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall5.png",
				spriteColorRect = { x = 1, y = 1, width = 6, height = 6 },
				uvRect = { u0 = 0.105469, v0 = 0.205078, u1 = 0.117188, v1 = 0.216797 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall6.png",
				spriteColorRect = { x = 1, y = 1, width = 6, height = 6 },
				uvRect = { u0 = 0.105469, v0 = 0.189453, u1 = 0.117188, v1 = 0.201172 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall7.png",
				spriteColorRect = { x = 2, y = 2, width = 4, height = 4 },
				uvRect = { u0 = 0.105469, v0 = 0.220703, u1 = 0.113281, v1 = 0.228516 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

