-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:0201ae0815efd4ae45210d6e7f6c738e:f1baafb3334c14af1e073e673ee4b890:3010a86129a0a3dbdaf9892eab1a8ec9$
-- 

return {
	texture = 'gameScene.png',
	frames = {
			{
				name = "UIdisplayitem.png",
				spriteColorRect = { x = 1, y = 3, width = 77, height = 50 },
				uvRect = { u0 = 0.105469, v0 = 0.779297, u1 = 0.203125, v1 = 0.929688 },
				spriteSourceSize = { width = 79, height = 56 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "UIenemybutton.png",
				spriteColorRect = { x = 0, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.0976562, v0 = 0.486328, u1 = 0.195312, v1 = 0.644531 },
				spriteSourceSize = { width = 81, height = 52 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "UIfriendlybutton.png",
				spriteColorRect = { x = 1, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.00390625, v0 = 0.78125, u1 = 0.101562, v1 = 0.939453 },
				spriteSourceSize = { width = 83, height = 52 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "UIresourcebar.png",
				spriteColorRect = { x = 1, y = 3, width = 149, height = 46 },
				uvRect = { u0 = 0.00390625, v0 = 0.486328, u1 = 0.09375, v1 = 0.777344 },
				spriteSourceSize = { width = 151, height = 54 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "attackIcon.png",
				spriteColorRect = { x = 6, y = 6, width = 52, height = 52 },
				uvRect = { u0 = 0.373047, v0 = 0.486328, u1 = 0.474609, v1 = 0.587891 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "base_01.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.486328, v0 = 0.236328, u1 = 0.568359, v1 = 0.308594 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_02.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.623047, v0 = 0.236328, u1 = 0.705078, v1 = 0.308594 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_03.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.902344, v0 = 0.160156, u1 = 0.984375, v1 = 0.232422 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_04.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.728516, v0 = 0.164062, u1 = 0.810547, v1 = 0.236328 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_05.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.816406, v0 = 0.160156, u1 = 0.898438, v1 = 0.232422 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_06.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.902344, v0 = 0.0839844, u1 = 0.984375, v1 = 0.15625 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_07.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.816406, v0 = 0.0839844, u1 = 0.898438, v1 = 0.15625 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_08.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.486328, v0 = 0.160156, u1 = 0.568359, v1 = 0.232422 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_09.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.486328, v0 = 0.0839844, u1 = 0.568359, v1 = 0.15625 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_10.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.623047, v0 = 0.160156, u1 = 0.705078, v1 = 0.232422 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_11.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.623047, v0 = 0.0839844, u1 = 0.705078, v1 = 0.15625 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "generator_01.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 61 },
				uvRect = { u0 = 0.300781, v0 = 0.486328, u1 = 0.369141, v1 = 0.605469 },
				spriteSourceSize = { width = 35, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "generator_02.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 61 },
				uvRect = { u0 = 0.3125, v0 = 0.925781, u1 = 0.431641, v1 = 0.994141 },
				spriteSourceSize = { width = 35, height = 61 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "generator_03.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 61 },
				uvRect = { u0 = 0.128906, v0 = 0.648438, u1 = 0.197266, v1 = 0.767578 },
				spriteSourceSize = { width = 35, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "interceptor_01.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 41 },
				uvRect = { u0 = 0.558594, v0 = 0.480469, u1 = 0.634766, v1 = 0.560547 },
				spriteSourceSize = { width = 39, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "interceptor_02.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 41 },
				uvRect = { u0 = 0.486328, v0 = 0.396484, u1 = 0.5625, v1 = 0.476562 },
				spriteSourceSize = { width = 39, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "interceptor_03.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 41 },
				uvRect = { u0 = 0.486328, v0 = 0.3125, u1 = 0.5625, v1 = 0.392578 },
				spriteSourceSize = { width = 39, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ringbutton.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.257812, v0 = 0.775391, u1 = 0.404297, v1 = 0.921875 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ringmenu.png",
				spriteColorRect = { x = 0, y = 0, width = 245, height = 245 },
				uvRect = { u0 = 0.00390625, v0 = 0.00390625, u1 = 0.482422, v1 = 0.482422 },
				spriteSourceSize = { width = 245, height = 245 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotBase_01.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.566406, v0 = 0.3125, u1 = 0.644531, v1 = 0.390625 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotBase_02.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.720703, v0 = 0.728516, u1 = 0.798828, v1 = 0.806641 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotBase_03.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.658203, v0 = 0.646484, u1 = 0.736328, v1 = 0.724609 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotBase_04.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.623047, v0 = 0.564453, u1 = 0.701172, v1 = 0.642578 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robot_down.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 44 },
				uvRect = { u0 = 0.408203, v0 = 0.722656, u1 = 0.494141, v1 = 0.824219 },
				spriteSourceSize = { width = 52, height = 44 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "robot_left.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 45 },
				uvRect = { u0 = 0.480469, v0 = 0.828125, u1 = 0.556641, v1 = 0.916016 },
				spriteSourceSize = { width = 39, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robot_right.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 46 },
				uvRect = { u0 = 0.478516, v0 = 0.486328, u1 = 0.554688, v1 = 0.576172 },
				spriteSourceSize = { width = 39, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robot_up.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 35 },
				uvRect = { u0 = 0.408203, v0 = 0.828125, u1 = 0.476562, v1 = 0.921875 },
				spriteSourceSize = { width = 48, height = 35 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket2_01.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.25, v0 = 0.486328, u1 = 0.296875, v1 = 0.636719 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocket2_02.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.207031, v0 = 0.775391, u1 = 0.253906, v1 = 0.925781 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocket2_03.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.158203, v0 = 0.933594, u1 = 0.308594, v1 = 0.980469 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket2_04.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.199219, v0 = 0.486328, u1 = 0.246094, v1 = 0.636719 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocket2_05.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.00390625, v0 = 0.943359, u1 = 0.154297, v1 = 0.990234 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_01.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.728516, v0 = 0.0839844, u1 = 0.8125, v1 = 0.160156 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_02.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.904297, v0 = 0.00390625, u1 = 0.988281, v1 = 0.0800781 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_03.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.816406, v0 = 0.00390625, u1 = 0.900391, v1 = 0.0800781 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_04.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.486328, v0 = 0.00390625, u1 = 0.570312, v1 = 0.0800781 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_05.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.623047, v0 = 0.00390625, u1 = 0.707031, v1 = 0.0800781 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_06.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.728516, v0 = 0.00390625, u1 = 0.8125, v1 = 0.0800781 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_07.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.648438, v0 = 0.84375, u1 = 0.724609, v1 = 0.927734 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_08.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.640625, v0 = 0.755859, u1 = 0.716797, v1 = 0.839844 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_09.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.568359, v0 = 0.871094, u1 = 0.644531, v1 = 0.955078 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_10.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.578125, v0 = 0.667969, u1 = 0.654297, v1 = 0.751953 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_11.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.560547, v0 = 0.783203, u1 = 0.636719, v1 = 0.867188 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_12.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.542969, v0 = 0.580078, u1 = 0.619141, v1 = 0.664062 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_13.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.542969, v0 = 0.580078, u1 = 0.619141, v1 = 0.664062 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_14.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.498047, v0 = 0.695312, u1 = 0.574219, v1 = 0.779297 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketBase_15.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.480469, v0 = 0.919922, u1 = 0.564453, v1 = 0.996094 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket_01.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 65 },
				uvRect = { u0 = 0.0976562, v0 = 0.648438, u1 = 0.125, v1 = 0.775391 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocket_02.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.294922, v0 = 0.640625, u1 = 0.322266, v1 = 0.771484 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocket_03.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.263672, v0 = 0.640625, u1 = 0.291016, v1 = 0.771484 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocket_04.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.232422, v0 = 0.640625, u1 = 0.259766, v1 = 0.771484 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocket_05.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.201172, v0 = 0.640625, u1 = 0.228516, v1 = 0.771484 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "turret.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 51 },
				uvRect = { u0 = 0.439453, v0 = 0.591797, u1 = 0.539062, v1 = 0.691406 },
				spriteSourceSize = { width = 51, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "upgradeIcon.png",
				spriteColorRect = { x = 4, y = 4, width = 56, height = 56 },
				uvRect = { u0 = 0.326172, v0 = 0.609375, u1 = 0.435547, v1 = 0.71875 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

