-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:84a958de6f1990f1c8859aa75c6694e2:494ba916bb80e06956cdea96fa50ec2f:3010a86129a0a3dbdaf9892eab1a8ec9$
-- 

return {
	texture = 'gameScene.png',
	frames = {
			{
				name = "base_01.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.351562, v0 = 0.738281, u1 = 0.515625, v1 = 0.810547 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_02.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.527344, v0 = 0.675781, u1 = 0.691406, v1 = 0.748047 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_03.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.703125, v0 = 0.638672, u1 = 0.867188, v1 = 0.710938 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_04.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.0078125, v0 = 0.708984, u1 = 0.171875, v1 = 0.78125 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_05.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.179688, v0 = 0.677734, u1 = 0.34375, v1 = 0.75 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_06.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.355469, v0 = 0.662109, u1 = 0.519531, v1 = 0.734375 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_07.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.53125, v0 = 0.599609, u1 = 0.695312, v1 = 0.671875 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_08.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.0078125, v0 = 0.632812, u1 = 0.171875, v1 = 0.705078 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_09.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.183594, v0 = 0.601562, u1 = 0.347656, v1 = 0.673828 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_10.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.359375, v0 = 0.585938, u1 = 0.523438, v1 = 0.658203 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "base_11.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 42 },
				uvRect = { u0 = 0.445312, v0 = 0.417969, u1 = 0.589844, v1 = 0.5 },
				spriteSourceSize = { width = 37, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expbig01.png",
				spriteColorRect = { x = 14, y = 14, width = 13, height = 11 },
				uvRect = { u0 = 0.871094, v0 = 0.128906, u1 = 0.921875, v1 = 0.150391 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig02.png",
				spriteColorRect = { x = 10, y = 10, width = 21, height = 19 },
				uvRect = { u0 = 0.410156, v0 = 0.261719, u1 = 0.492188, v1 = 0.298828 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig03.png",
				spriteColorRect = { x = 6, y = 6, width = 27, height = 25 },
				uvRect = { u0 = 0.488281, v0 = 0.324219, u1 = 0.59375, v1 = 0.373047 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig04.png",
				spriteColorRect = { x = 5, y = 5, width = 31, height = 29 },
				uvRect = { u0 = 0.5, v0 = 0.146484, u1 = 0.613281, v1 = 0.207031 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expbig05.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 39 },
				uvRect = { u0 = 0.832031, v0 = 0.238281, u1 = 0.992188, v1 = 0.314453 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expbig06.png",
				spriteColorRect = { x = 2, y = 0, width = 37, height = 37 },
				uvRect = { u0 = 0.347656, v0 = 0.814453, u1 = 0.492188, v1 = 0.886719 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig07.png",
				spriteColorRect = { x = 2, y = 1, width = 37, height = 35 },
				uvRect = { u0 = 0.476562, v0 = 0.890625, u1 = 0.613281, v1 = 0.962891 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expbig08.png",
				spriteColorRect = { x = 1, y = 1, width = 37, height = 35 },
				uvRect = { u0 = 0.332031, v0 = 0.890625, u1 = 0.46875, v1 = 0.962891 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expbig09.png",
				spriteColorRect = { x = 2, y = 1, width = 35, height = 35 },
				uvRect = { u0 = 0.6875, v0 = 0.796875, u1 = 0.824219, v1 = 0.865234 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig10.png",
				spriteColorRect = { x = 5, y = 3, width = 31, height = 31 },
				uvRect = { u0 = 0.871094, v0 = 0.173828, u1 = 0.992188, v1 = 0.234375 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig11.png",
				spriteColorRect = { x = 6, y = 4, width = 29, height = 29 },
				uvRect = { u0 = 0.5, v0 = 0.210938, u1 = 0.613281, v1 = 0.267578 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig12.png",
				spriteColorRect = { x = 6, y = 7, width = 27, height = 25 },
				uvRect = { u0 = 0.5, v0 = 0.271484, u1 = 0.605469, v1 = 0.320312 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expbig13.png",
				spriteColorRect = { x = 10, y = 6, width = 21, height = 25 },
				uvRect = { u0 = 0.410156, v0 = 0.208984, u1 = 0.492188, v1 = 0.257812 },
				spriteSourceSize = { width = 41, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expmid1.png",
				spriteColorRect = { x = 1, y = 1, width = 15, height = 16 },
				uvRect = { u0 = 0.933594, v0 = 0.00390625, u1 = 0.992188, v1 = 0.0351562 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expmid2.png",
				spriteColorRect = { x = 0, y = 1, width = 17, height = 18 },
				uvRect = { u0 = 0.359375, v0 = 0.458984, u1 = 0.429688, v1 = 0.492188 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expmid3.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.488281, v0 = 0.376953, u1 = 0.566406, v1 = 0.414062 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid4.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.402344, v0 = 0.34375, u1 = 0.480469, v1 = 0.380859 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid5.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.402344, v0 = 0.302734, u1 = 0.480469, v1 = 0.339844 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid6.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 20 },
				uvRect = { u0 = 0.539062, v0 = 0.105469, u1 = 0.617188, v1 = 0.142578 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "expmid7.png",
				spriteColorRect = { x = 1, y = 1, width = 17, height = 18 },
				uvRect = { u0 = 0.367188, v0 = 0.421875, u1 = 0.4375, v1 = 0.455078 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expmid8.png",
				spriteColorRect = { x = 0, y = 2, width = 17, height = 16 },
				uvRect = { u0 = 0.359375, v0 = 0.496094, u1 = 0.425781, v1 = 0.527344 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expmid9.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 18 },
				uvRect = { u0 = 0.367188, v0 = 0.384766, u1 = 0.4375, v1 = 0.417969 },
				spriteSourceSize = { width = 19, height = 20 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "expsmall1.png",
				spriteColorRect = { x = 3, y = 3, width = 2, height = 2 },
				uvRect = { u0 = 0.902344, v0 = 0.154297, u1 = 0.910156, v1 = 0.158203 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall2.png",
				spriteColorRect = { x = 0, y = 0, width = 8, height = 8 },
				uvRect = { u0 = 0.894531, v0 = 0.0742188, u1 = 0.925781, v1 = 0.0898438 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expsmall3.png",
				spriteColorRect = { x = 0, y = 0, width = 8, height = 8 },
				uvRect = { u0 = 0.894531, v0 = 0.0546875, u1 = 0.925781, v1 = 0.0703125 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "expsmall4.png",
				spriteColorRect = { x = 0, y = 1, width = 8, height = 6 },
				uvRect = { u0 = 0.894531, v0 = 0.09375, u1 = 0.925781, v1 = 0.105469 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall5.png",
				spriteColorRect = { x = 1, y = 1, width = 6, height = 6 },
				uvRect = { u0 = 0.871094, v0 = 0.154297, u1 = 0.894531, v1 = 0.166016 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall6.png",
				spriteColorRect = { x = 1, y = 1, width = 6, height = 6 },
				uvRect = { u0 = 0.894531, v0 = 0.109375, u1 = 0.917969, v1 = 0.121094 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expsmall7.png",
				spriteColorRect = { x = 2, y = 2, width = 4, height = 4 },
				uvRect = { u0 = 0.871094, v0 = 0.117188, u1 = 0.886719, v1 = 0.125 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "generator_01.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 61 },
				uvRect = { u0 = 0.253906, v0 = 0.136719, u1 = 0.492188, v1 = 0.205078 },
				spriteSourceSize = { width = 35, height = 61 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "generator_02.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 61 },
				uvRect = { u0 = 0.0078125, v0 = 0.136719, u1 = 0.246094, v1 = 0.205078 },
				spriteSourceSize = { width = 35, height = 61 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "generator_03.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 61 },
				uvRect = { u0 = 0.625, v0 = 0.117188, u1 = 0.863281, v1 = 0.185547 },
				spriteSourceSize = { width = 35, height = 61 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "interceptor_01.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 41 },
				uvRect = { u0 = 0.0078125, v0 = 0.865234, u1 = 0.160156, v1 = 0.945312 },
				spriteSourceSize = { width = 39, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "interceptor_02.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 41 },
				uvRect = { u0 = 0.0078125, v0 = 0.785156, u1 = 0.167969, v1 = 0.861328 },
				spriteSourceSize = { width = 39, height = 41 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "interceptor_03.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 41 },
				uvRect = { u0 = 0.179688, v0 = 0.753906, u1 = 0.339844, v1 = 0.830078 },
				spriteSourceSize = { width = 39, height = 41 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "robotBase_01.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.523438, v0 = 0.751953, u1 = 0.679688, v1 = 0.830078 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotBase_02.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.699219, v0 = 0.714844, u1 = 0.855469, v1 = 0.792969 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotBase_03.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.167969, v0 = 0.865234, u1 = 0.324219, v1 = 0.943359 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotBase_04.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.433594, v0 = 0.503906, u1 = 0.589844, v1 = 0.582031 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robot_down.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 44 },
				uvRect = { u0 = 0.621094, v0 = 0.189453, u1 = 0.824219, v1 = 0.275391 },
				spriteSourceSize = { width = 52, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robot_left.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 45 },
				uvRect = { u0 = 0.0078125, v0 = 0.3125, u1 = 0.183594, v1 = 0.388672 },
				spriteSourceSize = { width = 39, height = 45 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "robot_right.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 46 },
				uvRect = { u0 = 0.214844, v0 = 0.28125, u1 = 0.394531, v1 = 0.357422 },
				spriteSourceSize = { width = 39, height = 46 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "robot_up.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 35 },
				uvRect = { u0 = 0.214844, v0 = 0.208984, u1 = 0.402344, v1 = 0.277344 },
				spriteSourceSize = { width = 48, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocket2_01.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.316406, v0 = 0.0546875, u1 = 0.617188, v1 = 0.101562 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket2_02.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.0078125, v0 = 0.0546875, u1 = 0.308594, v1 = 0.101562 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket2_03.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.625, v0 = 0.00390625, u1 = 0.925781, v1 = 0.0507812 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket2_04.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.316406, v0 = 0.00390625, u1 = 0.617188, v1 = 0.0507812 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket2_05.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 77 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.308594, v1 = 0.0507812 },
				spriteSourceSize = { width = 24, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_01.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.773438, v0 = 0.558594, u1 = 0.941406, v1 = 0.634766 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_02.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.597656, v0 = 0.519531, u1 = 0.765625, v1 = 0.595703 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_03.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.773438, v0 = 0.478516, u1 = 0.941406, v1 = 0.554688 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_04.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.597656, v0 = 0.439453, u1 = 0.765625, v1 = 0.515625 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_05.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.777344, v0 = 0.398438, u1 = 0.945312, v1 = 0.474609 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_06.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.0078125, v0 = 0.552734, u1 = 0.175781, v1 = 0.628906 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_07.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.183594, v0 = 0.521484, u1 = 0.351562, v1 = 0.597656 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_08.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.0078125, v0 = 0.472656, u1 = 0.175781, v1 = 0.548828 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_09.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.183594, v0 = 0.441406, u1 = 0.351562, v1 = 0.517578 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_10.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.601562, v0 = 0.359375, u1 = 0.769531, v1 = 0.435547 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_11.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.789062, v0 = 0.318359, u1 = 0.957031, v1 = 0.394531 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_12.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.0078125, v0 = 0.392578, u1 = 0.175781, v1 = 0.46875 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_13.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.0078125, v0 = 0.392578, u1 = 0.175781, v1 = 0.46875 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_14.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.191406, v0 = 0.361328, u1 = 0.359375, v1 = 0.4375 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocketBase_15.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 43 },
				uvRect = { u0 = 0.613281, v0 = 0.279297, u1 = 0.78125, v1 = 0.355469 },
				spriteSourceSize = { width = 39, height = 43 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket_01.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 65 },
				uvRect = { u0 = 0.277344, v0 = 0.105469, u1 = 0.53125, v1 = 0.132812 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "rocket_02.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.0078125, v0 = 0.105469, u1 = 0.269531, v1 = 0.132812 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket_03.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.625, v0 = 0.0859375, u1 = 0.886719, v1 = 0.113281 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket_04.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.625, v0 = 0.0546875, u1 = 0.886719, v1 = 0.0820312 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "rocket_05.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 67 },
				uvRect = { u0 = 0.933594, v0 = 0.0390625, u1 = 0.988281, v1 = 0.169922 },
				spriteSourceSize = { width = 14, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "turret.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 51 },
				uvRect = { u0 = 0.0078125, v0 = 0.208984, u1 = 0.207031, v1 = 0.308594 },
				spriteSourceSize = { width = 51, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

