-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:79727813ead4b64c22e26da21958260e:8cae8e1ac6c12aae146df6efa76396f7:109a633fbcccdf9dd8adc72b3a4e0e61$
-- 

return {
	texture = 'gui.png',
	frames = {
			{
				name = "UIdialog.png",
				spriteColorRect = { x = 0, y = 0, width = 210, height = 77 },
				uvRect = { u0 = 0.486328, v0 = 0.00390625, u1 = 0.896484, v1 = 0.154297 },
				spriteSourceSize = { width = 210, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "UIdisplayitem.png",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 54 },
				uvRect = { u0 = 0.486328, v0 = 0.361328, u1 = 0.652344, v1 = 0.466797 },
				spriteSourceSize = { width = 85, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "UIdisplayitemhighlight.png",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 54 },
				uvRect = { u0 = 0.486328, v0 = 0.251953, u1 = 0.652344, v1 = 0.357422 },
				spriteSourceSize = { width = 85, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "UIenemybutton.png",
				spriteColorRect = { x = 0, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.699219, v0 = 0.373047, u1 = 0.857422, v1 = 0.470703 },
				spriteSourceSize = { width = 81, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "UIfriendlybutton.png",
				spriteColorRect = { x = 1, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.728516, v0 = 0.271484, u1 = 0.886719, v1 = 0.369141 },
				spriteSourceSize = { width = 83, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "UIresourcebar.png",
				spriteColorRect = { x = 1, y = 3, width = 149, height = 46 },
				uvRect = { u0 = 0.486328, v0 = 0.158203, u1 = 0.777344, v1 = 0.248047 },
				spriteSourceSize = { width = 151, height = 54 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowdown.png",
				spriteColorRect = { x = 1, y = 1, width = 14, height = 19 },
				uvRect = { u0 = 0.890625, v0 = 0.34375, u1 = 0.917969, v1 = 0.380859 },
				spriteSourceSize = { width = 16, height = 21 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowleft.png",
				spriteColorRect = { x = 2, y = 2, width = 20, height = 13 },
				uvRect = { u0 = 0.65625, v0 = 0.351562, u1 = 0.695312, v1 = 0.376953 },
				spriteSourceSize = { width = 24, height = 17 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowright'.png",
				spriteColorRect = { x = 1, y = 1, width = 21, height = 13 },
				uvRect = { u0 = 0.65625, v0 = 0.322266, u1 = 0.697266, v1 = 0.347656 },
				spriteSourceSize = { width = 23, height = 15 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowup.png",
				spriteColorRect = { x = 1, y = 1, width = 14, height = 18 },
				uvRect = { u0 = 0.65625, v0 = 0.380859, u1 = 0.683594, v1 = 0.416016 },
				spriteSourceSize = { width = 16, height = 20 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "attackIcon.png",
				spriteColorRect = { x = 6, y = 6, width = 52, height = 52 },
				uvRect = { u0 = 0.894531, v0 = 0.164062, u1 = 0.996094, v1 = 0.265625 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ringbutton.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.486328, v0 = 0.470703, u1 = 0.632812, v1 = 0.617188 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ringmenu.png",
				spriteColorRect = { x = 0, y = 0, width = 245, height = 245 },
				uvRect = { u0 = 0.00390625, v0 = 0.00390625, u1 = 0.482422, v1 = 0.482422 },
				spriteSourceSize = { width = 245, height = 245 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "selector1.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 40 },
				uvRect = { u0 = 0.900391, v0 = 0.00390625, u1 = 0.980469, v1 = 0.0820312 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "selector2.png",
				spriteColorRect = { x = 1, y = 1, width = 39, height = 38 },
				uvRect = { u0 = 0.900391, v0 = 0.0859375, u1 = 0.976562, v1 = 0.160156 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "selector3.png",
				spriteColorRect = { x = 2, y = 2, width = 37, height = 36 },
				uvRect = { u0 = 0.894531, v0 = 0.269531, u1 = 0.966797, v1 = 0.339844 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "selector4.png",
				spriteColorRect = { x = 3, y = 3, width = 35, height = 34 },
				uvRect = { u0 = 0.65625, v0 = 0.251953, u1 = 0.724609, v1 = 0.318359 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "upgradeIcon.png",
				spriteColorRect = { x = 4, y = 4, width = 56, height = 56 },
				uvRect = { u0 = 0.78125, v0 = 0.158203, u1 = 0.890625, v1 = 0.267578 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

