-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:f6fca55030dc940750c62c8bd45b2e85:4566808b7780c39107d3b57cf1eaf175:109a633fbcccdf9dd8adc72b3a4e0e61$
-- 

return {
	texture = 'gui.png',
	frames = {
			{
				name = "UIdialog.png",
				spriteColorRect = { x = 0, y = 0, width = 210, height = 77 },
				uvRect = { u0 = 0.0078125, v0 = 0.486328, u1 = 0.828125, v1 = 0.636719 },
				spriteSourceSize = { width = 210, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "UIdisplayitem.png",
				spriteColorRect = { x = 1, y = 3, width = 77, height = 50 },
				uvRect = { u0 = 0.535156, v0 = 0.742188, u1 = 0.835938, v1 = 0.839844 },
				spriteSourceSize = { width = 79, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "UIenemybutton.png",
				spriteColorRect = { x = 0, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.21875, v0 = 0.892578, u1 = 0.535156, v1 = 0.990234 },
				spriteSourceSize = { width = 81, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "UIfriendlybutton.png",
				spriteColorRect = { x = 1, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.597656, v0 = 0.640625, u1 = 0.914062, v1 = 0.738281 },
				spriteSourceSize = { width = 83, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "UIresourcebar.png",
				spriteColorRect = { x = 1, y = 3, width = 149, height = 46 },
				uvRect = { u0 = 0.0078125, v0 = 0.640625, u1 = 0.589844, v1 = 0.730469 },
				spriteSourceSize = { width = 151, height = 54 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "attackIcon.png",
				spriteColorRect = { x = 6, y = 6, width = 52, height = 52 },
				uvRect = { u0 = 0.0078125, v0 = 0.892578, u1 = 0.210938, v1 = 0.994141 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ringbutton.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.0078125, v0 = 0.742188, u1 = 0.300781, v1 = 0.888672 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ringmenu.png",
				spriteColorRect = { x = 0, y = 0, width = 245, height = 245 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.964844, v1 = 0.482422 },
				spriteSourceSize = { width = 245, height = 245 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "upgradeIcon.png",
				spriteColorRect = { x = 4, y = 4, width = 56, height = 56 },
				uvRect = { u0 = 0.308594, v0 = 0.734375, u1 = 0.527344, v1 = 0.84375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

