-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:38817cf0e88bcbbe5aa6e84a24d8509c:b1df19a20633280193ce62dad3d40eee:109a633fbcccdf9dd8adc72b3a4e0e61$
-- 

return {
	texture = 'gui.png',
	frames = {
			{
				name = "UIdialog.png",
				spriteColorRect = { x = 0, y = 0, width = 210, height = 77 },
				uvRect = { u0 = 0.486328, v0 = 0.00195312, u1 = 0.896484, v1 = 0.0771484 },
				spriteSourceSize = { width = 210, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "UIdisplayitem.png",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 54 },
				uvRect = { u0 = 0.119141, v0 = 0.103516, u1 = 0.285156, v1 = 0.15625 },
				spriteSourceSize = { width = 85, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "UIdisplayitemhighlight.png",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 54 },
				uvRect = { u0 = 0.119141, v0 = 0.0488281, u1 = 0.285156, v1 = 0.101562 },
				spriteSourceSize = { width = 85, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "UIenemybutton.png",
				spriteColorRect = { x = 0, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.289062, v0 = 0.113281, u1 = 0.447266, v1 = 0.162109 },
				spriteSourceSize = { width = 81, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "UIfriendlybutton.png",
				spriteColorRect = { x = 1, y = 1, width = 81, height = 50 },
				uvRect = { u0 = 0.486328, v0 = 0.0791016, u1 = 0.644531, v1 = 0.12793 },
				spriteSourceSize = { width = 83, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "UIresourcebar.png",
				spriteColorRect = { x = 1, y = 3, width = 149, height = 46 },
				uvRect = { u0 = 0.119141, v0 = 0.00195312, u1 = 0.410156, v1 = 0.046875 },
				spriteSourceSize = { width = 151, height = 54 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowdown.png",
				spriteColorRect = { x = 1, y = 1, width = 14, height = 19 },
				uvRect = { u0 = 0.451172, v0 = 0.0888672, u1 = 0.478516, v1 = 0.107422 },
				spriteSourceSize = { width = 16, height = 21 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowleft.png",
				spriteColorRect = { x = 2, y = 2, width = 20, height = 13 },
				uvRect = { u0 = 0.404297, v0 = 0.0888672, u1 = 0.443359, v1 = 0.101562 },
				spriteSourceSize = { width = 24, height = 17 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowright.png",
				spriteColorRect = { x = 1, y = 1, width = 21, height = 13 },
				uvRect = { u0 = 0.414062, v0 = 0.0371094, u1 = 0.455078, v1 = 0.0498047 },
				spriteSourceSize = { width = 23, height = 15 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arrowup.png",
				spriteColorRect = { x = 1, y = 1, width = 14, height = 18 },
				uvRect = { u0 = 0.451172, v0 = 0.109375, u1 = 0.478516, v1 = 0.126953 },
				spriteSourceSize = { width = 16, height = 20 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "attackIcon.png",
				spriteColorRect = { x = 6, y = 6, width = 52, height = 52 },
				uvRect = { u0 = 0.761719, v0 = 0.0791016, u1 = 0.863281, v1 = 0.129883 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "destroyIcon.png",
				spriteColorRect = { x = 0, y = 0, width = 57, height = 64 },
				uvRect = { u0 = 0.289062, v0 = 0.0488281, u1 = 0.400391, v1 = 0.111328 },
				spriteSourceSize = { width = 57, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ringbutton.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.119141, v0 = 0.158203, u1 = 0.265625, v1 = 0.231445 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ringmenu.png",
				spriteColorRect = { x = 0, y = 0, width = 245, height = 245 },
				uvRect = { u0 = 0.00390625, v0 = 0.753906, u1 = 0.482422, v1 = 0.993164 },
				spriteSourceSize = { width = 245, height = 245 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "selector1.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 40 },
				uvRect = { u0 = 0.900391, v0 = 0.00195312, u1 = 0.980469, v1 = 0.0410156 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "selector2.png",
				spriteColorRect = { x = 1, y = 1, width = 39, height = 38 },
				uvRect = { u0 = 0.900391, v0 = 0.0429688, u1 = 0.976562, v1 = 0.0800781 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "selector3.png",
				spriteColorRect = { x = 2, y = 2, width = 37, height = 36 },
				uvRect = { u0 = 0.404297, v0 = 0.0517578, u1 = 0.476562, v1 = 0.0869141 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "selector4.png",
				spriteColorRect = { x = 3, y = 3, width = 35, height = 34 },
				uvRect = { u0 = 0.414062, v0 = 0.00195312, u1 = 0.482422, v1 = 0.0351562 },
				spriteSourceSize = { width = 41, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "splitter.png",
				spriteColorRect = { x = 0, y = 0, width = 57, height = 768 },
				uvRect = { u0 = 0.00390625, v0 = 0.00195312, u1 = 0.115234, v1 = 0.751953 },
				spriteSourceSize = { width = 57, height = 768 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "upgradeIcon.png",
				spriteColorRect = { x = 4, y = 4, width = 56, height = 56 },
				uvRect = { u0 = 0.648438, v0 = 0.0791016, u1 = 0.757812, v1 = 0.133789 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

