-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:935e1a77e424c9313447029713f14bd9:1/1$
-- 

return {
	texture = 'test.png',
	frames = {
			{
				name = "coin1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.484375, v0 = 0.472656, u1 = 0.609375, v1 = 0.53125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin2.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.867188, v0 = 0.378906, u1 = 0.992188, v1 = 0.4375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin3.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.828125, v0 = 0.605469, u1 = 0.953125, v1 = 0.65625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin4.png",
				spriteColorRect = { x = 4, y = 0, width = 22, height = 32 },
				uvRect = { u0 = 0.375, v0 = 0.519531, u1 = 0.460938, v1 = 0.582031 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin5.png",
				spriteColorRect = { x = 10, y = 0, width = 10, height = 32 },
				uvRect = { u0 = 0.925781, v0 = 0.00390625, u1 = 0.964844, v1 = 0.0664062 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin6.png",
				spriteColorRect = { x = 4, y = 0, width = 22, height = 32 },
				uvRect = { u0 = 0.242188, v0 = 0.519531, u1 = 0.367188, v1 = 0.5625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin7.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.828125, v0 = 0.550781, u1 = 0.953125, v1 = 0.601562 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin8.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.492188, v0 = 0.410156, u1 = 0.617188, v1 = 0.46875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core1.png",
				spriteColorRect = { x = 11, y = 11, width = 42, height = 52 },
				uvRect = { u0 = 0.617188, v0 = 0.527344, u1 = 0.820312, v1 = 0.609375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core2.png",
				spriteColorRect = { x = 11, y = 9, width = 42, height = 54 },
				uvRect = { u0 = 0.625, v0 = 0.441406, u1 = 0.835938, v1 = 0.523438 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core3.png",
				spriteColorRect = { x = 11, y = 5, width = 42, height = 58 },
				uvRect = { u0 = 0.0078125, v0 = 0.464844, u1 = 0.234375, v1 = 0.546875 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core4.png",
				spriteColorRect = { x = 11, y = 3, width = 42, height = 60 },
				uvRect = { u0 = 0.625, v0 = 0.355469, u1 = 0.859375, v1 = 0.4375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core5.png",
				spriteColorRect = { x = 11, y = 3, width = 42, height = 60 },
				uvRect = { u0 = 0.625, v0 = 0.355469, u1 = 0.859375, v1 = 0.4375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core6.png",
				spriteColorRect = { x = 11, y = 5, width = 42, height = 58 },
				uvRect = { u0 = 0.0078125, v0 = 0.464844, u1 = 0.234375, v1 = 0.546875 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core7.png",
				spriteColorRect = { x = 11, y = 9, width = 42, height = 54 },
				uvRect = { u0 = 0.625, v0 = 0.441406, u1 = 0.835938, v1 = 0.523438 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core8.png",
				spriteColorRect = { x = 11, y = 11, width = 42, height = 52 },
				uvRect = { u0 = 0.617188, v0 = 0.527344, u1 = 0.820312, v1 = 0.609375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_bk1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.492188, v0 = 0.347656, u1 = 0.617188, v1 = 0.40625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_bk2.png",
				spriteColorRect = { x = 2, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.867188, v0 = 0.316406, u1 = 0.992188, v1 = 0.375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_fr1.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.867188, v0 = 0.25, u1 = 0.992188, v1 = 0.3125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "man1_fr2.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.25, v0 = 0.28125, u1 = 0.375, v1 = 0.34375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "man1_lf1.png",
				spriteColorRect = { x = 3, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.84375, v0 = 0.496094, u1 = 0.96875, v1 = 0.546875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_lf2.png",
				spriteColorRect = { x = 6, y = 0, width = 20, height = 32 },
				uvRect = { u0 = 0.46875, v0 = 0.578125, u1 = 0.59375, v1 = 0.617188 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_rt1.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.84375, v0 = 0.441406, u1 = 0.96875, v1 = 0.492188 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_rt2.png",
				spriteColorRect = { x = 6, y = 0, width = 20, height = 32 },
				uvRect = { u0 = 0.46875, v0 = 0.535156, u1 = 0.59375, v1 = 0.574219 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "robotfront1.png",
				spriteColorRect = { x = 11, y = 1, width = 42, height = 60 },
				uvRect = { u0 = 0.0078125, v0 = 0.378906, u1 = 0.242188, v1 = 0.460938 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "robotfront2.png",
				spriteColorRect = { x = 11, y = 3, width = 42, height = 58 },
				uvRect = { u0 = 0.25, v0 = 0.433594, u1 = 0.476562, v1 = 0.515625 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "robotfront2_1.png",
				spriteColorRect = { x = 0, y = 1, width = 64, height = 62 },
				uvRect = { u0 = 0.667969, v0 = 0.00390625, u1 = 0.917969, v1 = 0.125 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "robotfront2_2.png",
				spriteColorRect = { x = 0, y = 3, width = 64, height = 60 },
				uvRect = { u0 = 0.667969, v0 = 0.128906, u1 = 0.917969, v1 = 0.246094 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "robotfront2_3.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.410156, v0 = 0.00390625, u1 = 0.660156, v1 = 0.128906 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotfront3.png",
				spriteColorRect = { x = 11, y = 1, width = 42, height = 60 },
				uvRect = { u0 = 0.25, v0 = 0.347656, u1 = 0.484375, v1 = 0.429688 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "rocket.png",
				spriteColorRect = { x = 0, y = 0, width = 101, height = 78 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.402344, v1 = 0.15625 },
				spriteSourceSize = { width = 101, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketbaseback1.png",
				spriteColorRect = { x = 2, y = 5, width = 60, height = 52 },
				uvRect = { u0 = 0.625, v0 = 0.25, u1 = 0.859375, v1 = 0.351562 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbaseback2.png",
				spriteColorRect = { x = 2, y = 5, width = 60, height = 52 },
				uvRect = { u0 = 0.382812, v0 = 0.242188, u1 = 0.617188, v1 = 0.34375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbaseback3.png",
				spriteColorRect = { x = 2, y = 3, width = 60, height = 54 },
				uvRect = { u0 = 0.0078125, v0 = 0.269531, u1 = 0.242188, v1 = 0.375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbaseback4.png",
				spriteColorRect = { x = 2, y = 3, width = 60, height = 54 },
				uvRect = { u0 = 0.0078125, v0 = 0.160156, u1 = 0.242188, v1 = 0.265625 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbaseback5.png",
				spriteColorRect = { x = 2, y = 3, width = 60, height = 54 },
				uvRect = { u0 = 0.410156, v0 = 0.132812, u1 = 0.644531, v1 = 0.238281 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbasefront1.png",
				spriteColorRect = { x = 2, y = 31, width = 60, height = 32 },
				uvRect = { u0 = 0.25, v0 = 0.160156, u1 = 0.375, v1 = 0.277344 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

