-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:ae6e26b0d93f984a49953d44e209f859:1/1$
-- 

return {
	texture = 'test.png',
	frames = {
			{
				name = "coin1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.53125, v0 = 0.015625, u1 = 0.765625, v1 = 0.265625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin2.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.265625, v0 = 0.546875, u1 = 0.5, v1 = 0.796875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin3.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.75, v0 = 0.28125, u1 = 0.953125, v1 = 0.53125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin4.png",
				spriteColorRect = { x = 4, y = 0, width = 22, height = 32 },
				uvRect = { u0 = 0.28125, v0 = 0.8125, u1 = 0.53125, v1 = 0.984375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin5.png",
				spriteColorRect = { x = 10, y = 0, width = 10, height = 32 },
				uvRect = { u0 = 0.546875, v0 = 0.890625, u1 = 0.796875, v1 = 0.96875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin6.png",
				spriteColorRect = { x = 4, y = 0, width = 22, height = 32 },
				uvRect = { u0 = 0.015625, v0 = 0.8125, u1 = 0.265625, v1 = 0.984375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin7.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.515625, v0 = 0.546875, u1 = 0.71875, v1 = 0.796875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin8.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.28125, v0 = 0.28125, u1 = 0.515625, v1 = 0.53125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_bk1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.015625, v0 = 0.546875, u1 = 0.25, v1 = 0.796875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_bk2.png",
				spriteColorRect = { x = 2, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.28125, v0 = 0.015625, u1 = 0.515625, v1 = 0.265625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_fr1.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.015625, v0 = 0.28125, u1 = 0.265625, v1 = 0.53125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "man1_fr2.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.015625, v0 = 0.015625, u1 = 0.265625, v1 = 0.265625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "man1_lf1.png",
				spriteColorRect = { x = 3, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.53125, v0 = 0.28125, u1 = 0.734375, v1 = 0.53125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_lf2.png",
				spriteColorRect = { x = 6, y = 0, width = 20, height = 32 },
				uvRect = { u0 = 0.734375, v0 = 0.71875, u1 = 0.984375, v1 = 0.875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_rt1.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.78125, v0 = 0.015625, u1 = 0.984375, v1 = 0.265625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_rt2.png",
				spriteColorRect = { x = 6, y = 0, width = 20, height = 32 },
				uvRect = { u0 = 0.734375, v0 = 0.546875, u1 = 0.984375, v1 = 0.703125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

