-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:385ab2a422844685f5b815403e316bc4:12a47982c9d57a6071f7fc3e032c6b82:9c519dc4da464f2a30daa98e61c4961f$
-- 

return {
	texture = 'test.png',
	frames = {
			{
				name = "attackIcon.png",
				spriteColorRect = { x = 6, y = 6, width = 52, height = 52 },
				uvRect = { u0 = 0.246094, v0 = 0.894531, u1 = 0.347656, v1 = 0.996094 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.890625, v0 = 0.0664062, u1 = 0.953125, v1 = 0.125 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin2.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.824219, v0 = 0.046875, u1 = 0.886719, v1 = 0.105469 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin3.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.710938, v0 = 0.171875, u1 = 0.773438, v1 = 0.222656 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin4.png",
				spriteColorRect = { x = 4, y = 0, width = 22, height = 32 },
				uvRect = { u0 = 0.824219, v0 = 0.164062, u1 = 0.886719, v1 = 0.207031 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin5.png",
				spriteColorRect = { x = 10, y = 0, width = 10, height = 32 },
				uvRect = { u0 = 0.154297, v0 = 0.607422, u1 = 0.216797, v1 = 0.626953 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin6.png",
				spriteColorRect = { x = 4, y = 0, width = 22, height = 32 },
				uvRect = { u0 = 0.777344, v0 = 0.117188, u1 = 0.820312, v1 = 0.179688 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin7.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.710938, v0 = 0.117188, u1 = 0.773438, v1 = 0.167969 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "coin8.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.923828, v0 = 0.00390625, u1 = 0.986328, v1 = 0.0625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "core.png",
				spriteColorRect = { x = 10, y = 1, width = 50, height = 62 },
				uvRect = { u0 = 0.253906, v0 = 0.765625, u1 = 0.351562, v1 = 0.886719 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core1.png",
				spriteColorRect = { x = 11, y = 11, width = 42, height = 52 },
				uvRect = { u0 = 0.486328, v0 = 0.113281, u1 = 0.568359, v1 = 0.214844 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core2.png",
				spriteColorRect = { x = 11, y = 9, width = 42, height = 54 },
				uvRect = { u0 = 0.486328, v0 = 0.00390625, u1 = 0.568359, v1 = 0.109375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core3.png",
				spriteColorRect = { x = 11, y = 5, width = 42, height = 58 },
				uvRect = { u0 = 0.625, v0 = 0.845703, u1 = 0.707031, v1 = 0.958984 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core4.png",
				spriteColorRect = { x = 11, y = 3, width = 42, height = 60 },
				uvRect = { u0 = 0.488281, v0 = 0.607422, u1 = 0.570312, v1 = 0.724609 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core5.png",
				spriteColorRect = { x = 11, y = 3, width = 42, height = 60 },
				uvRect = { u0 = 0.488281, v0 = 0.607422, u1 = 0.570312, v1 = 0.724609 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core6.png",
				spriteColorRect = { x = 11, y = 5, width = 42, height = 58 },
				uvRect = { u0 = 0.625, v0 = 0.845703, u1 = 0.707031, v1 = 0.958984 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core7.png",
				spriteColorRect = { x = 11, y = 9, width = 42, height = 54 },
				uvRect = { u0 = 0.486328, v0 = 0.00390625, u1 = 0.568359, v1 = 0.109375 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "core8.png",
				spriteColorRect = { x = 11, y = 11, width = 42, height = 52 },
				uvRect = { u0 = 0.486328, v0 = 0.113281, u1 = 0.568359, v1 = 0.214844 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "demolishIcon.png",
				spriteColorRect = { x = 4, y = 2, width = 56, height = 60 },
				uvRect = { u0 = 0.275391, v0 = 0.486328, u1 = 0.384766, v1 = 0.603516 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "generator.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.00390625, v0 = 0.765625, u1 = 0.128906, v1 = 0.890625 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "interceptor_active.png",
				spriteColorRect = { x = 2, y = 2, width = 60, height = 60 },
				uvRect = { u0 = 0.257812, v0 = 0.607422, u1 = 0.375, v1 = 0.724609 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "interceptor_idle.png",
				spriteColorRect = { x = 1, y = 16, width = 60, height = 46 },
				uvRect = { u0 = 0.388672, v0 = 0.486328, u1 = 0.478516, v1 = 0.603516 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_bk1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.574219, v0 = 0.0703125, u1 = 0.632812, v1 = 0.132812 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_bk2.png",
				spriteColorRect = { x = 2, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.574219, v0 = 0.00390625, u1 = 0.632812, v1 = 0.0664062 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_fr1.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.636719, v0 = 0.0703125, u1 = 0.699219, v1 = 0.132812 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "man1_fr2.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.636719, v0 = 0.00390625, u1 = 0.699219, v1 = 0.0664062 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "man1_lf1.png",
				spriteColorRect = { x = 3, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.890625, v0 = 0.128906, u1 = 0.953125, v1 = 0.179688 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_lf2.png",
				spriteColorRect = { x = 6, y = 0, width = 20, height = 32 },
				uvRect = { u0 = 0.957031, v0 = 0.132812, u1 = 0.996094, v1 = 0.195312 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "man1_rt1.png",
				spriteColorRect = { x = 2, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.824219, v0 = 0.109375, u1 = 0.886719, v1 = 0.160156 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "man1_rt2.png",
				spriteColorRect = { x = 6, y = 0, width = 20, height = 32 },
				uvRect = { u0 = 0.957031, v0 = 0.0664062, u1 = 0.996094, v1 = 0.128906 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mech.png",
				spriteColorRect = { x = 11, y = 3, width = 42, height = 58 },
				uvRect = { u0 = 0.550781, v0 = 0.728516, u1 = 0.632812, v1 = 0.841797 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ringbutton.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.00390625, v0 = 0.486328, u1 = 0.150391, v1 = 0.632812 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ringmenu.png",
				spriteColorRect = { x = 0, y = 0, width = 245, height = 245 },
				uvRect = { u0 = 0.00390625, v0 = 0.00390625, u1 = 0.482422, v1 = 0.482422 },
				spriteSourceSize = { width = 245, height = 245 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotfront1.png",
				spriteColorRect = { x = 11, y = 1, width = 42, height = 60 },
				uvRect = { u0 = 0.464844, v0 = 0.728516, u1 = 0.546875, v1 = 0.845703 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "robotfront2.png",
				spriteColorRect = { x = 11, y = 3, width = 42, height = 58 },
				uvRect = { u0 = 0.539062, v0 = 0.849609, u1 = 0.621094, v1 = 0.962891 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "robotfront2_1.png",
				spriteColorRect = { x = 0, y = 1, width = 64, height = 62 },
				uvRect = { u0 = 0.132812, v0 = 0.636719, u1 = 0.253906, v1 = 0.761719 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "robotfront2_2.png",
				spriteColorRect = { x = 0, y = 3, width = 64, height = 60 },
				uvRect = { u0 = 0.132812, v0 = 0.765625, u1 = 0.25, v1 = 0.890625 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "robotfront2_3.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.00390625, v0 = 0.636719, u1 = 0.128906, v1 = 0.761719 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "robotfront3.png",
				spriteColorRect = { x = 11, y = 1, width = 42, height = 60 },
				uvRect = { u0 = 0.482422, v0 = 0.486328, u1 = 0.564453, v1 = 0.603516 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocket.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 20 },
				uvRect = { u0 = 0.824219, v0 = 0.00390625, u1 = 0.919922, v1 = 0.0429688 },
				spriteSourceSize = { width = 49, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rocketLauncher.png",
				spriteColorRect = { x = 2, y = 3, width = 60, height = 60 },
				uvRect = { u0 = 0.154297, v0 = 0.486328, u1 = 0.271484, v1 = 0.603516 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbaseback1.png",
				spriteColorRect = { x = 2, y = 5, width = 60, height = 52 },
				uvRect = { u0 = 0.125, v0 = 0.894531, u1 = 0.242188, v1 = 0.996094 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbaseback2.png",
				spriteColorRect = { x = 2, y = 5, width = 60, height = 52 },
				uvRect = { u0 = 0.00390625, v0 = 0.894531, u1 = 0.121094, v1 = 0.996094 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbaseback3.png",
				spriteColorRect = { x = 2, y = 3, width = 60, height = 54 },
				uvRect = { u0 = 0.378906, v0 = 0.607422, u1 = 0.484375, v1 = 0.724609 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "rocketbaseback4.png",
				spriteColorRect = { x = 2, y = 3, width = 60, height = 54 },
				uvRect = { u0 = 0.355469, v0 = 0.728516, u1 = 0.460938, v1 = 0.845703 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "rocketbaseback5.png",
				spriteColorRect = { x = 2, y = 3, width = 60, height = 54 },
				uvRect = { u0 = 0.351562, v0 = 0.890625, u1 = 0.46875, v1 = 0.996094 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rocketbasefront1.png",
				spriteColorRect = { x = 2, y = 31, width = 60, height = 32 },
				uvRect = { u0 = 0.472656, v0 = 0.849609, u1 = 0.535156, v1 = 0.966797 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "upgradeIcon.png",
				spriteColorRect = { x = 4, y = 4, width = 56, height = 56 },
				uvRect = { u0 = 0.710938, v0 = 0.00390625, u1 = 0.820312, v1 = 0.113281 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

